# 공통 부분
# docker 컨테이너 버전을 명시
version: '3.8'

# services는 컨테이너
services:
  container_name: acoha-container
  acoha-next:
    # -it 옵션을 위해 사용됨 (표준입출력)
    stdin_open: true
    tty: true
    # 현재 경로에 이미지 빌드
    build:
      context: .
