# 가져올 이미지를 정의
FROM node:18-alpine
# 경로 설정하기
WORKDIR /app
# package.json 워킹 디렉토리에 복사
COPY package* yarn.lock .pnp* ./
COPY .yarnrc.yml ./
COPY .yarn ./.yarn
# 의존성 설치
RUN yarn --immutable
COPY . .

# 3000번 포트 노출
EXPOSE 3001
# yarn dev 스크립트 실행
CMD ["yarn", "dev"]