# 가져올 이미지를 정의
FROM node:18-alpine AS builder
# 경로 설정하기
WORKDIR /app
# package.json 워킹 디렉토리에 복사
COPY package.json yarn.lock .pnp* ./
COPY .yarnrc.yml ./
COPY .yarn ./.yarn
# 의존성 설치
RUN yarn --immutable
# 의존성 설치 후 현재 디렉토리의 모든 파일을 도커 컨테이너의 워킹 디렉토리에 복사한다.
COPY . .
# product 빌드 == next build
RUN yarn build

# 3000번 포트 노출
EXPOSE 3000
# yarn dev 스크립트 실행
CMD ["yarn","start"]