# docker 컨테이너 버전을 명시
version: '3.8'

# services는 컨테이너
services:
  acoha-next:
    container_name: acoha-next
    # 현재 경로에 이미지 빌드
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    volumes:
      - ./src:/app/src:ro
    env_file:
      - .env
