import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Example from '@/atom/Headless';
import Example2 from '@/atom/Switch';
import Example3 from '@/atom/Menu';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title css>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link href="/dist/output.css" rel="stylesheet"></link> */}
      </Head>

      <main
        css={{
          backgroundColor: 'yellow',
        }}
        className={styles.main}
      >
        <Example />
        <Example2 />
        <Example3 />
        <div
          css={(theme) => ({
            fontSize: theme.fontSizes.sm,
            backgroundColor: 'yellow',
          })}
        >
          안녕하세요dsafsa
        </div>
        <div className="text-3xl font-bold underline text-black">
          감사합니다
        </div>
      </main>
    </>
  );
}
