import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { Test } from '@/components/test';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title css>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Test />
      <main
        css={{
          backgroundColor: 'yellow',
        }}
        className={styles.main}
      >
        <div
          css={(theme) => ({
            fontSize: theme.fontSizes.sm,
            backgroundColor: 'yellow',
          })}
        >
          안녕하세요dsafsa
        </div>
      </main>
    </>
  );
}
